#=================================================
# https://github.com/yangchuansheng/docker-image
# Description: Build and push tailscale-mikrotik Docker image
# Lisence: MIT
# Author: Carson Yang
# Blog: https://icloudnative.io
#=================================================

name: Build and push tailscale-mikrotik Docker image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'tailscale-mikrotik/**'
      - '.github/workflows/tailscale-mikrotik.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'tailscale-mikrotik/**'
      - '.github/workflows/tailscale-mikrotik.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Login to GitHub Package Registry
      env:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
      run: echo ${{ env.password }} | docker login ghcr.io -u ${{ env.username }} --password-stdin
      
    - name: Prepare
      run: |-
        cd tailscale-mikrotik
        git clone https://github.com/tailscale/tailscale.git
        cd tailscale && eval $(./build_dist.sh shellvars) && cd ..

    # Runs a single command using the runners shell
    - name: Build and push Docker images to docker.io and ghcr.io
      uses: docker/build-push-action@v2
      with:
        file: 'tailscale-mikrotik/Dockerfile'
        platforms: linux/amd64
        context: tailscale-mikrotik
        push: true
        tags: |
          yangchuansheng/tailscale-mikrotik:latest
          ghcr.io/yangchuansheng/tailscale-mikrotik:latest
